---
name: GitHub Actions Exercise3

on:
  - push

jobs:
  python-setup-matrix:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        platform: ["ubuntu-22.04"]
    
    runs-on: ${{ matrix.platform }}
    
    steps:
      - uses: actions/checkout@v4
      - name: "Setup Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - run: |
          python3 --version
